name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  test:
    needs: generate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - id: stack
        uses: freckle/stack-action@v5
        env:
          STACK_YAML: ${{ matrix.stack-yaml }}

  required-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: freckle/await-statuses-action@v1
        with:
          statuses: |
            test (stack.yaml)
            test (stack-lts-20.26.yaml)
            test (stack-lts-21.25.yaml)

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
          path: '["yield/library/", "yield/tests/"]'
